### ISSUE TITLE
float value should be decimal?

### ISSUE THREAD

**Issue by fnoop** [Kiwa21/mavros-maverick#1]
After updating ACRO_RP_P to 4.500001, I get this notification from mavros-maverick:
```
param_id: "ACRO_RP_P"
param_value: 4.50000095367
param_type: 9
param_count: 884
param_index: 65535
```
param_value is defined as float so can't be represented correctly.  Is this just a presentation issue, or as it is actually stored within mavros?

**Comment by Kiwa21** [comment]
Fixed
Using floor and pow functions seems to correct the rounding.
`float_tmp = static_cast<double>(pmsg.param_value);
                float_tmp = floor(pow(10,7)*float_tmp)/pow(10,7);
                param_msg.param_value = float_tmp;`
